[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "/plugins/sentry-netlify-build-plugin"

  [plugins.inputs]
    sentryOrg="leander-test"
    sentryProject="leander-test-next"
    sentryRepository="my-custom-name"